# -*- coding: utf-8 -*-
"""3. Bert_resume_shortlisting_COMPLETE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lr4uuVXxSLWxbWyqLHtHxes2fx9qUhDz

With BERT (DistilBERT)
"""

!pip install matplotlib

!pip install tensorflow

!pip install pdfplumber
!pip install PyPDF2
!pip install -U spacy
!python -m spacy download en_core_web_lg

import os
import numpy as np
import tensorflow as tf
from transformers import AutoTokenizer, TFAutoModel
from sklearn.metrics.pairwise import cosine_similarity
import PyPDF2
import spacy

# Load spaCy NLP model
nlp = spacy.load("en_core_web_sm")

# Initialize Tokenizer and Model
tokenizer = AutoTokenizer.from_pretrained("manishiitg/distilbert-resume-parts-classify")
model = TFAutoModel.from_pretrained("manishiitg/distilbert-resume-parts-classify", from_pt=True)

!unzip /content/drive/MyDrive/HireAIML.zip -d '/content/HireAIML'

# 1. Extract Text from PDFs
def extract_text_from_pdf(pdf_path):
    text = ""
    with open(pdf_path, 'rb') as file:
        reader = PyPDF2.PdfReader(file)
        for page in reader.pages:
            text += page.extract_text()
    return text

# 2. Preprocess Text
nlp = spacy.load("en_core_web_sm")
def preprocess_text(text):
    doc = nlp(text.lower())
    return " ".join([token.lemma_ for token in doc if not token.is_stop and not token.is_punct])

# 3. Tokenize and Get Embeddings
def get_embeddings(text):
    inputs = tokenizer(text, return_tensors="tf", truncation=True, padding=True, max_length=512)
    outputs = model(**inputs)
    return outputs.last_hidden_state[:, 0, :].numpy()  # CLS token embedding

# 4. Compute Similarity Scores
def compute_similarity(job_desc_embedding, resume_embeddings):
    similarities = cosine_similarity(job_desc_embedding, resume_embeddings)
    return similarities[0]

# 5. Shortlist Top Candidates
def shortlist_resumes(job_desc, resumes_folder, top_k=5):
    # Step 1: Extract and preprocess job description
    job_desc_text = extract_text_from_pdf(job_desc)
    job_desc_processed = preprocess_text(job_desc_text)
    # print(len(job_desc_processed))
    job_desc_embedding = get_embeddings(job_desc_processed)


    # Step 2: Process and embed resumes
    resume_scores = []
    resume_embeddings = []
    resume_files = os.listdir(resumes_folder)

    for resume_file in resume_files:
        resume_path = os.path.join(resumes_folder, resume_file)
        resume_text = extract_text_from_pdf(resume_path)
        resume_processed = preprocess_text(resume_text)
        resume_embedding = get_embeddings(resume_processed)
        # print(resume_embedding.shape)

        # Compute similarity
        score = cosine_similarity(job_desc_embedding, resume_embedding)[0][0]
        resume_scores.append((resume_file, score))
        resume_embeddings.append(resume_embedding)

    # Step 3: Rank resumes by similarity
    resume_scores.sort(key=lambda x: x[1], reverse=True) #reverseTrue is descending order
    print(resume_scores)
    top_candidates = resume_scores[:top_k]

    return top_candidates, resume_scores

# Example Usage
job_description_pdf = "/content/HireAIML/HireAMLE/dataset/Job description.pdf"
resumes_folder = "/content/HireAIML/HireAMLE/dataset/testResumes"

top_candidates, all_resume_scores = shortlist_resumes(job_description_pdf, resumes_folder)

# top_candidates = shortlist_resumes(job_description_pdf, resumes_folder)
for candidate in top_candidates:
    print(f"Resume: {candidate[0]}, Similarity Score: {candidate[1]:.2f}")

print(top_candidates)  # Check the first 5 entries

print(f"{'Candidate No.':<15} {'Similarity Score':<15}")
print("-" * 30)

for filename, score in top_candidates:
    candidate_no = filename.split("_")[1].split(".")[0]  # Extract number from 'candidate_039.pdf'
    print(f"{candidate_no:<15} {score:.4f}")

import matplotlib.pyplot as plt

def plot_similarity_distribution(resumes_folder):
    scores = [float(score) for _, score in resumes_folder]
    plt.hist(scores, bins=20, color='skyblue', edgecolor='black')
    plt.title("Resume Similarity Score Distribution")
    plt.xlabel("Similarity Score")
    plt.ylabel("Number of Resumes")
    plt.grid(True)
    plt.show()

# plot_similarity_distribution(top_candidates)
plot_similarity_distribution(all_resume_scores)

"""What this says about your code's credibility:

Your similarity model differentiates well between more and less relevant resumes.

The distribution looks like a normal-ish bell shape, meaning it’s not biased or skewed towards very high or low scores.

The spread helps you decide a good threshold — e.g., you might only consider resumes above 0.45 as “strong matches.”
"""

import matplotlib.pyplot as plt

def plot_similarity_distribution(resume_scores):
    scores = [float(score) for _, score in resume_scores]
    plt.hist(scores, bins=20, color='skyblue', edgecolor='black')
    plt.title("Resume Similarity Score Distribution")
    plt.xlabel("Similarity Score")
    plt.ylabel("Number of Resumes")
    plt.grid(True)
    plt.show()

plot_similarity_distribution(top_candidates)

# import umap
# import matplotlib.pyplot as plt
# import seaborn as sns
# import numpy as np

# # Extract embeddings
# resume_embeddings = np.array([candidate[2] for candidate in top_candidates])  # Assuming candidate[2] is embedding
# job_desc_embedding = job_desc_embedding.reshape(1, -1)

# # Reduce to 2D for visualization
# reducer = umap.UMAP(n_components=2, random_state=42)
# reduced_embeddings = reducer.fit_transform(np.vstack([job_desc_embedding] + resume_embeddings))

# # Split points for plotting
# all_resumes = reduced_embeddings[1:]  # All resumes
# top_5_indices = [top_candidates.index(candidate) + 1 for candidate in top_candidates[:5]]  # Indices in reduced embeddings
# top_5_points = reduced_embeddings[top_5_indices]  # Top 5 closest resumes

# # Create scatter plot
# plt.figure(figsize=(12, 8))
# sns.scatterplot(x=all_resumes[:, 0], y=all_resumes[:, 1], color="gray", alpha=0.6, label="All Resumes")
# sns.scatterplot(x=[reduced_embeddings[0, 0]], y=[reduced_embeddings[0, 1]], color="red", marker="*", s=300, label="Job Description")
# sns.scatterplot(x=top_5_points[:, 0], y=top_5_points[:, 1], color="blue", s=150, label="Top 5 Closest Resumes", edgecolor="black", linewidth=1.2)

# # Annotate top 5 resumes
# for i, (x, y) in enumerate(top_5_points):
#     plt.text(x, y, f"Top {i+1}", fontsize=12, fontweight='bold', ha='right', color='

